CLINICAL_TRIALS_TABLE_SQL = """
create table if not exists clinical_trials (
  nct_id text primary key,
  requested_nct_id text,
  org_study_id text,
  acronym text,
  nct_aliases jsonb,
  secondary_ids jsonb,
  brief_title text,
  official_title text,
  sponsor_name text,
  sponsor_class text,
  collaborators jsonb,
  responsible_party jsonb,
  overall_status text,
  why_stopped text,
  status_verified_date text,
  has_results boolean,
  expanded_access boolean,
  study_type text,
  phases jsonb,
  phase_label text,
  phase_score integer,
  allocation text,
  intervention_model text,
  primary_purpose text,
  masking text,
  enrollment_count integer,
  enrollment_type text,
  therapeutic_area text,
  conditions jsonb,
  condition_keywords jsonb,
  interventions jsonb,
  intervention_names jsonb,
  intervention_types jsonb,
  arm_groups jsonb,
  primary_outcomes jsonb,
  secondary_outcomes jsonb,
  other_outcomes jsonb,
  primary_endpoint_measures jsonb,
  secondary_endpoint_measures jsonb,
  brief_summary text,
  detailed_description text,
  eligibility_criteria text,
  healthy_volunteers boolean,
  sex text,
  minimum_age text,
  maximum_age text,
  std_ages jsonb,
  fda_regulated_drug boolean,
  fda_regulated_device boolean,
  has_dmc boolean,
  start_date text,
  primary_completion_date text,
  completion_date text,
  study_first_posted text,
  results_first_posted text,
  last_update_posted text,
  event_date_candidate text,
  event_date_source text,
  event_date_precision text,
  locations jsonb,
  location_count integer,
  country_counts jsonb,
  us_site_count integer,
  trial_references jsonb,
  reference_count integer,
  see_also_links jsonb,
  keyword_hits jsonb,
  derived_misc_info jsonb,
  central_contacts jsonb,
  overall_officials jsonb,
  ipd_sharing text,
  source_system text default 'clinicaltrials.gov',
  source_api_version text default 'v2',
  has_sponsor boolean,
  has_primary_outcomes boolean,
  has_secondary_outcomes boolean,
  has_locations boolean,
  has_interventions boolean,
  has_reference_support boolean,
  has_eligibility boolean,
  has_event_date boolean,
  has_results_flag boolean,
  data_completeness_score integer,
  data_completeness_ratio double precision,
  ingested_at timestamptz default now(),
  updated_at timestamptz default now()
);
"""


CLINICAL_TRIALS_INDEX_SQL = [
    "create index if not exists clinical_trials_sponsor_name_idx on clinical_trials (sponsor_name);",
    "create index if not exists clinical_trials_overall_status_idx on clinical_trials (overall_status);",
    "create index if not exists clinical_trials_phase_score_idx on clinical_trials (phase_score);",
    "create index if not exists clinical_trials_therapeutic_area_idx on clinical_trials (therapeutic_area);",
    "create index if not exists clinical_trials_event_date_candidate_idx on clinical_trials (event_date_candidate);",
    "create index if not exists clinical_trials_has_results_idx on clinical_trials (has_results);",
]


TRIAL_ANALYSES_TABLE_SQL = """
create table if not exists trial_analyses (
  analysis_id bigserial primary key,
  nct_id text not null references clinical_trials (nct_id) on delete cascade,
  requested_nct_id text,
  mapped_ticker text,
  mapped_cik text,
  sponsor_name text,
  event_date_candidate text,
  event_date_source text,
  overall_status text,
  phase_label text,
  therapeutic_area text,
  approval_record_count integer,
  market_record_count integer,
  event_day_return double precision,
  post_window_return double precision,
  warning_count integer not null default 0,
  analysis_version text not null default '1.0',
  analysis_payload jsonb not null,
  created_at timestamptz default now()
);
"""


TRIAL_ANALYSES_INDEX_SQL = [
    "create index if not exists trial_analyses_nct_id_idx on trial_analyses (nct_id);",
    "create index if not exists trial_analyses_mapped_ticker_idx on trial_analyses (mapped_ticker);",
    "create index if not exists trial_analyses_created_at_idx on trial_analyses (created_at desc);",
]
